version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      # step function deploy
      - sam build --template $(pwd)/template.yaml
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name shadow-deployment-stack --capabilities CAPABILITY_NAMED_IAM --s3-bucket $BUCKET --s3-prefix deployements --no-fail-on-empty-changeset